forward theme to storyboardApp
ilikerobots/storyboard pull request #7
Opened 2019-12-11 22:44 UTC by heralight

2019-12-17 14:58 UTC, ilikerobots requested changes
Hey, great idea. Thanks!  But before I accept, could you please 
  a) keep the stories as a required parameter
  b) autoformat the file?

2020-01-13 16:32 UTC, heralight commented
done.

2020-01-15 16:50 UTC, ilikerobots approved these changes

2020-01-15 16:50 UTC, merged

2020-01-15 16:52 UTC, ilikerobots commented
Thanks.  I'll release in the next day or two